//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDADES
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class adecuacionIscFiuplaEntities : DbContext
    {
        public adecuacionIscFiuplaEntities()
            : base("name=adecuacionIscFiuplaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adecuacion> adecuacion { get; set; }
        public virtual DbSet<detalleAdecuacion> detalleAdecuacion { get; set; }
        public virtual DbSet<equivalenciaAsignatura> equivalenciaAsignatura { get; set; }
        public virtual DbSet<estudiante> estudiante { get; set; }
    }
}
