//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDADES
{
    using System;
    using System.Collections.Generic;
    
    public partial class adecuacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public adecuacion()
        {
            this.detalleAdecuacion = new HashSet<detalleAdecuacion>();
        }
    
        public int idAdecuacion { get; set; }
        public string codigoAdecuacion { get; set; }
        public string futAdecuacion { get; set; }
        public System.DateTime fechaRecepcion { get; set; }
        public string periodo { get; set; }
        public System.DateTime fechaEmision { get; set; }
        public int idEstudiante { get; set; }
    
        public virtual estudiante estudiante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalleAdecuacion> detalleAdecuacion { get; set; }
    }
}
