//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDADES
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class detalleAdecuacion
    {
        [Display(Name="ID")]
        public int idDetalle { get; set; }
        public int idAdecuacion { get; set; }
        public int idEquivalencia { get; set; }
        public string notaAsignaturaA { get; set; }
        public string notaAsignaturaB { get; set; }
        public System.DateTime fechaActa { get; set; }
    
        public virtual adecuacion adecuacion { get; set; }
        public virtual equivalenciaAsignatura equivalenciaAsignatura { get; set; }
    }
}
